### ISSUE TITLE
Error when Create Kafka Receiver on Zeppelin

### ISSUE THREAD

**Issue by azzam-krya** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#10] opened 2016-12-09 06:24 UTC
Hi Ahmad,
When I run Kafka receiver on zeppelin i got an error

My dependencies:
org.apache.kafka:kafka_2.11:0.8.2.1
org.apache.spark:spark-streaming-kafka-assembly_2.11:1.6.3
com.twitter:algebird-core_2.11:0.12.3

Error Message:
java.lang.NoClassDefFoundError: org/apache/spark/Logging at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:760) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) at java.net.URLClassLoader.access$100(URLClassLoader.java:73) at java.net.URLClassLoader$1.run(URLClassLoader.java:368) at java.net.URLClassLoader$1.run(URLClassLoader.java:362) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:361) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at org.apache.spark.streaming.kafka.KafkaUtils$.createStream(KafkaUtils.scala:91)

I already try to make dependeny version same like video but still same result 
I already try vagrant reload and vagrant reload --provision and still same result

**Comment by aalkilani** [comment] 2016-12-09 19:28
Duplicate of #8 
Issue now documented as part of troubleshooting guide here: https://github.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture/blob/master/vagrant/troubleshooting.md#zeppelin

Short of it is, use the following instead:

```
org.apache.kafka:kafka_2.11:0.8.2.1 
org.apache.spark:spark-streaming-kafka-0-8_2.11:2.0.2 
com.twitter:algebird-core_2.11:0.12.3
```

**Closed as completed by aalkilani** 2016-12-09 19:28 UTC
