### ISSUE TITLE
vagrant up gives an error

### ISSUE THREAD

**Issue by moszinet** [aalkilani/spark-kafka-cassandra-applying-lambda-architecture#3] opened 2016-11-24 12:51 UTC
Hi Ahmad,

it seems that vagrant up gives the following error: 
default: Box 'aalkilani/spark-kafka-cassandra-applying-lambda-architecture' could not be found.

**Comment by aalkilani** [comment] 2016-11-25 20:05
This is duplicate of #2 and is a problem with vagrant on Mac OS X. 

This is a problem with vagrant on OS X as documented here: mitchellh/vagrant#7970
See troubleshooting guide for a workaround:
https://github.com/aalkilani/spark-kafka-cassandra-applying-lambda-architecture/blob/master/vagrant/troubleshooting.md

This stackoverflow discussion also goes through some details:
http://stackoverflow.com/questions/40473943/vagrant-box-could-not-be-found-or-could-not-be-accessed-in-the-remote-catalog

**Closed as completed by aalkilani** 2016-11-25 20:05 UTC
